language: c

env:
  - TARGET=all

addons:
  apt:
    packages:
      - pkg-config
      - libnotify-dev
      - libgtk-3-dev

compiler:
  - clang
  #- gcc # Come back to this later

script: make clean all install
